import nodemailer from "nodemailer";
import { IMeeting } from "../models/Meeting";
import { IActionItem } from "../models/ActionItem";

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT) || 587,
  secure: process.env.SMTP_SECURE === "true",
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function buildHtml(meeting: IMeeting, actions: IActionItem[]): string {
  const actionRows = actions
    .map(
      (a) => `<tr>
        <td style="padding:12px 10px;border-bottom:1px solid #e6e6e6">${a.task}</td>
        <td style="padding:12px 10px;border-bottom:1px solid #e6e6e6">${a.assignee}</td>
        <td style="padding:12px 10px;border-bottom:1px solid #e6e6e6">${a.dueDate?.toLocaleDateString() ?? "—"}</td>
      </tr>`,
    )
    .join("");

  const decisions = meeting.decisions
    .map((d) => `<li style="margin:6px 0">${d}</li>`)
    .join("");

  return `
    <div style="font-family:Arial,Helvetica,sans-serif;max-width:720px;margin:auto;color:#1c1c1c;line-height:1.6">
      <div style="padding:24px;border:1px solid #e8e8e8;border-radius:16px;background:#ffffff">
        <h1 style="font-size:24px;color:#111;margin-bottom:8px">Minutes of Meeting</h1>
        <p style="color:#555;margin-top:0">${meeting.title} • ${new Date(meeting.date).toLocaleDateString()}</p>

        <div style="margin-top:24px">
          <p style="margin:0"><strong>Participants:</strong> ${meeting.participants
            .map((p) => p.name)
            .join(", ")}</p>
        </div>

        <section style="margin-top:28px">
          <h2 style="font-size:18px;color:#111;margin-bottom:10px">Executive summary</h2>
          <p style="margin:0;color:#444">${meeting.summary}</p>
        </section>

        <section style="margin-top:24px">
          <h2 style="font-size:18px;color:#111;margin-bottom:10px">Decisions</h2>
          <ul style="margin:0;padding-left:18px;color:#444">${decisions}</ul>
        </section>

        <section style="margin-top:24px">
          <h2 style="font-size:18px;color:#111;margin-bottom:10px">Action items</h2>
          <table style="width:100%;border-collapse:collapse;font-size:14px">
            <thead>
              <tr style="background:#f4f6f8;text-align:left">
                <th style="padding:12px 10px">Task</th>
                <th style="padding:12px 10px">Owner</th>
                <th style="padding:12px 10px">Due date</th>
              </tr>
            </thead>
            <tbody>${actionRows}</tbody>
          </table>
        </section>

        <p style="margin-top:32px;font-size:13px;color:#888">Generated by AI Meeting MOM Generator</p>
      </div>
    </div>`;
}

export async function sendMOM(
  meeting: IMeeting,
  actions: IActionItem[],
): Promise<void> {
  const to = meeting.participants.map((p) => p.email).join(", ");
  console.log("[Email] sending participant MOM", {
    meetingId: meeting._id,
    title: meeting.title,
    to,
    participantEmails: meeting.participants.map((participant) => participant.email),
    actionAssigneeEmails: actions.map((action) => ({
      task: action.task,
      assignee: action.assignee,
      assigneeEmail: action.assigneeEmail,
    })),
  });

  const info = await transporter.sendMail({
    from: `"MOM Generator" <${process.env.SMTP_USER}>`,
    to,
    subject: `MOM: ${meeting.title} • ${new Date(meeting.date).toLocaleDateString()}`,
    html: buildHtml(meeting, actions),
  });

  console.log("[Email] participant MOM accepted by SMTP", {
    meetingId: meeting._id,
    messageId: info.messageId,
    accepted: info.accepted,
    rejected: info.rejected,
    response: info.response,
  });
}

export async function sendTranscriptReadyEmail(
  hostName: string,
  hostEmail: string,
  meeting: IMeeting,
): Promise<void> {
  const meetingUrl = process.env.FRONTEND_URL
    ? `${process.env.FRONTEND_URL}/meetings/${meeting._id}`
    : "";

  console.log("[Email] sending host transcript-ready email", {
    meetingId: meeting._id,
    title: meeting.title,
    hostName,
    hostEmail,
    meetingUrl,
  });

  const info = await transporter.sendMail({
    from: `"MOM Generator" <${process.env.SMTP_USER}>`,
    to: hostEmail,
    subject: `Transcript ready: ${meeting.title}`,
    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;color:#1c1c1c;line-height:1.5;max-width:680px;margin:auto">
        <h1 style="font-size:22px;margin-bottom:8px">Your transcript is ready</h1>
        <p>Hi ${hostName},</p>
        <p>The transcript and generated MOM for <strong>${meeting.title}</strong> are ready.</p>
        <p><strong>Meeting date:</strong> ${new Date(meeting.date).toLocaleString()}</p>
        ${
          meetingUrl
            ? `<a href="${meetingUrl}" style="display:inline-block;padding:12px 18px;background:#111827;color:#fff;border-radius:8px;text-decoration:none;margin-top:16px">View transcript</a>`
            : ""
        }
        <p style="margin-top:24px;color:#666;font-size:13px">Participant emails and action items were saved in your MOM dashboard. Participant emails are not sent automatically unless you click Send MOM email.</p>
      </div>`,
  });

  console.log("[Email] host transcript-ready accepted by SMTP", {
    meetingId: meeting._id,
    messageId: info.messageId,
    accepted: info.accepted,
    rejected: info.rejected,
    response: info.response,
  });
}

export async function sendWelcomeEmail(
  name: string,
  email: string,
): Promise<void> {
  await transporter.sendMail({
    from: `"MOM Generator" <${process.env.SMTP_USER}>`,
    to: email,
    subject: "Welcome to MOM Generator",
    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;color:#1c1c1c;line-height:1.5">
        <h1>Welcome, ${name}</h1>
        <p>Thanks for signing up. Your meeting minutes and action items will now be captured, organized, and emailed automatically.</p>
      </div>`,
  });
}

export async function sendPasswordReset(
  email: string,
  resetUrl: string,
): Promise<void> {
  await transporter.sendMail({
    from: `"MOM Generator" <${process.env.SMTP_USER}>`,
    to: email,
    subject: "Reset your MOM Generator password",
    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;color:#1c1c1c;line-height:1.5">
        <h1>Password reset request</h1>
        <p>Click the link below to choose a new password. The link expires in 30 minutes.</p>
        <a href="${resetUrl}" style="display:inline-block;padding:12px 18px;background:#0066cc;color:#fff;border-radius:8px;text-decoration:none;margin-top:16px">Reset password</a>
      </div>`,
  });
}

export async function sendActionReminder(
  assigneeEmail: string,
  assigneeName: string,
  task: string,
  dueDate?: Date,
): Promise<void> {
  console.log("[Email] sending action reminder", {
    assigneeEmail,
    assigneeName,
    task,
    dueDate,
  });

  const info = await transporter.sendMail({
    from: `"MOM Reminder" <${process.env.SMTP_USER}>`,
    to: assigneeEmail,
    subject: `Reminder: ${task}`,
    html: `
      <div style="font-family:Arial,Helvetica,sans-serif;color:#1c1c1c;line-height:1.5">
        <p>Hi ${assigneeName},</p>
        <p>This is a reminder for your assigned task:</p>
        <blockquote style="border-left:4px solid #0066cc;padding-left:12px;margin:16px 0;">${task}</blockquote>
        <p>Due date: <strong>${dueDate?.toLocaleDateString() ?? "Soon"}</strong></p>
        <p>Please update the status in the MOM portal.</p>
      </div>`,
  });

  console.log("[Email] action reminder accepted by SMTP", {
    messageId: info.messageId,
    accepted: info.accepted,
    rejected: info.rejected,
    response: info.response,
  });
}
